### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by amalhajo** [TheIncredibles3445/ParkingApp#10]

**Comment by lamees97** [comment]
26-27 March:( done)
- started with sms feature
- show a custom alert when the admin click on any report 
- sending an sms message to the user 
[parkingLamees.zip](https://github.com/TheIncredibles3445/ParkingApp/files/4397490/parkingLamees.zip)

**Comment by lamees97** [comment]
30-31 March:
- fixed some bugs showed while sending sms.
- send the sms from admin to user 
[parkingLamees (2).zip](https://github.com/TheIncredibles3445/ParkingApp/files/4416797/parkingLamees.2.zip)

**Comment by lamees97** [comment]
April 1st :
-  update the status of the reports from false to true 
after sending the SMS to the user.
- list all the reports with status= false (unsolved) to the admin.
[parkingLamees (2).zip](https://github.com/TheIncredibles3445/ParkingApp/files/4416824/parkingLamees.2.zip)

**Comment by lamees97** [comment]
finished the SMS feature.
