### ISSUE TITLE
Parking Booking

### ISSUE THREAD

**Issue by amalhajo** [TheIncredibles3445/ParkingApp#2]

**Comment by TheIncredibles3445** [comment]
Friday 20/03
- Took a small break from working on this features to get the idea right.
- So took up a task on fixing some of the small tasks, such as user editing their profile, user adding their vehicle, and user adding their payment card. 
- So started with working on the making the edit profile screen.
- Completed the edit profile screen by the end of the day.

**Comment by TheIncredibles3445** [comment]
Finished parking booking and closing it
