### ISSUE TITLE
User Reports

### ISSUE THREAD

**Issue by amalhajo** [TheIncredibles3445/ParkingApp#3]

**Comment by lamees97** [comment]
Tuesday (March 17,2020):
- I was working on date and time of the users reports.
- I searched and tried some packages that can handle both date and time together.
- I installed a packege for date and time that goes well with react native which called 
datePicker.
- I worked on storing the user the reports ti
[parking (3).zip](https://github.com/TheIncredibles3445/ParkingApp/files/4356807/parking.3.zip)
[parking (3).zip](https://github.com/TheIncredibles3445/ParkingApp/files/4356810/parking.3.zip)

me and date in the database and I made it worked. so when the user select the date and the time, 
it will store in the database after he submit the report.
- I made couple of researches for letting the user take a picture of the problem or upload from his Photos.
- At the end, I installed expo-Permissions package for the image part and 
 

Wednesday (March 18, 2020):
- I started with figuring out how to handle the user current location in the report.
- I searched for different packages that will handle the location in expo and react native.
- I installed expo-location package.
- I faced a problem when I was adding the location which was the report stopped saving in the database
- The rest of the day I tried to fix that problem.

Thursday (March 19, 2020):
- I created a page for admin management called AdminPanel.
- this page will have a button, so when the admin clicks on this button it will show to him all the reports.
- To make that worked, I used react native navigation and stack navigation.

**Comment by lamees97** [comment]
March 20,2020:
- I fixed some bugs in the image part and I showed the image in the App
- I stored the image as well in firebase storage and stored it in the database as a URL
- I displayed the image beside the description of the report using Avatar componenent from react-native-elements
- I added one more field to the report which is the car number for the one who did the problem called "plateNumber"
- I stored the plateNumber in the Reports collection in the database.



March 21,2020:
- I started working on admin managment feature for user reports.
- first, I started with giving points to user by the admin.for now I made it like when the user submit the report it will add 50 points to his points. 
- I started doing the search part to let the admin search for the user who made the problem.
- I fixed the problem that I faced which was when I listed all the plate numbers it shows the same numbers for all the reports. 
- I spent some time to style and design our app.
[parkingLamees-updated.zip](https://github.com/TheIncredibles3445/ParkingApp/files/4389100/parkingLamees-updated.zip)
